# Generated by Django 5.0 on 2023-12-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
