# Generated by Django 5.0 on 2023-12-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
